name: Minecraft NPC Bot
on:
  workflow_dispatch:
jobs:
  run-bot:
    runs-on: ubuntu-latest
    timeout-minutes: 340
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install mineflayer
      - run: node bot.js
